// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// SN74HC595 //
// --------- //

#define SN74HC595_wrap_target 0
#define SN74HC595_wrap 4

static const uint16_t SN74HC595_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0     
    0xe05f, //  1: set    y, 31           side 0     
    0x6001, //  2: out    pins, 1         side 0     
    0x1082, //  3: jmp    y--, 2          side 2     
    0x6801, //  4: out    pins, 1         side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program SN74HC595_program = {
    .instructions = SN74HC595_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config SN74HC595_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + SN74HC595_wrap_target, offset + SN74HC595_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

