// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// ws2812x2 //
// -------- //

#define ws2812x2_wrap_target 0
#define ws2812x2_wrap 5

static const uint16_t ws2812x2_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xe057, //  1: set    y, 23                      
    0xe501, //  2: set    pins, 1                [5] 
    0x6801, //  3: out    pins, 1                [8] 
    0xee00, //  4: set    pins, 0                [14]
    0x0082, //  5: jmp    y--, 2                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws2812x2_program = {
    .instructions = ws2812x2_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config ws2812x2_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ws2812x2_wrap_target, offset + ws2812x2_wrap);
    return c;
}
#endif

