// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// charlieplexing //
// -------------- //

#define charlieplexing_wrap_target 0
#define charlieplexing_wrap 10

static const uint16_t charlieplexing_program_instructions[] = {
            //     .wrap_target
    0x8080, //  0: pull   noblock                    
    0xa027, //  1: mov    x, osr                     
    0xe000, //  2: set    pins, 0                    
    0x6083, //  3: out    pindirs, 3                 
    0x7f03, //  4: out    pins, 3                [31]
    0xff5f, //  5: set    y, 31                  [31]
    0x1f86, //  6: jmp    y--, 6                 [31]
    0x7f03, //  7: out    pins, 3                [31]
    0xff5f, //  8: set    y, 31                  [31]
    0x1f89, //  9: jmp    y--, 9                 [31]
    0x00e2, // 10: jmp    !osre, 2                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program charlieplexing_program = {
    .instructions = charlieplexing_program_instructions,
    .length = 11,
    .origin = -1,
};

static inline pio_sm_config charlieplexing_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + charlieplexing_wrap_target, offset + charlieplexing_wrap);
    return c;
}
#endif

